# Generated by Django 4.2.6 on 2023-10-25 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('about_me', models.CharField(max_length=150, verbose_name='О себе')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('phone', models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Введите номер телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Введите логин telegram', regex='^@[\\w\\d_]{5,32}$')], verbose_name='Telegram')),
                ('experience', models.PositiveSmallIntegerField(verbose_name='Опыт')),
                ('activity', models.PositiveSmallIntegerField(verbose_name='Активность')),
                ('photo', models.ImageField(default=None, upload_to='applicants/images/', verbose_name='Фотография соискателя')),
                ('resume_pdf', models.FilePathField(blank=True, null=True, path='applicants/resumes/', verbose_name='Резюме в формате pdf')),
                ('resume_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на резюме')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на портфолио')),
            ],
            options={
                'verbose_name': 'Соискатель',
                'verbose_name_plural': 'Соискатели',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название')),
                ('position', models.CharField(max_length=150, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='specialization',
            constraint=models.UniqueConstraint(fields=('name', 'position'), name='unique_specialization'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.grade', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(related_name='applicants', to='applicants.skill', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.specialization', verbose_name='Специализация'),
        ),
    ]
