# Generated by Django 4.2.6 on 2023-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_favorites_remove_applicant_grade_delete_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='specialization',
            field=models.ManyToManyField(related_name='skills', to='applicants.specialization', verbose_name='Специализация'),
        ),
    ]
