# Generated by Django 4.2.6 on 2023-10-29 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_skill_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Введите номер телефона', regex='^(\\+\\d{1,4}\\s?)?(\\d{1,4}[\\s-]?)?(\\(\\d{1,}\\)[\\s-]?)?\\d{1,}([\\s-]?\\d{1,}){1,}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='applicants/images/', verbose_name='Фотография соискателя'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='applicants/resumes/', verbose_name='Резюме в формате pdf'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='applicants.skill', verbose_name='Навыки'),
        ),
    ]
