repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files


  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        exclude: (migrations)
        args: [ --profile, black, --line-length=79, --src-path, hr_system ]


  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: (migrations)
        args: [ --line-length=79 ]
