version: "3.8"

services:
  hr-system-db:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - hr-system-db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  hr-system:
    build: .
    depends_on:
      - hr-system-db
    ports:
      - "8000:8000"
    volumes:
      - ./hr_system:/code
    environment:
      - DB_HOST=hr-system-db
    env_file:
      - ./.env

volumes:
  hr-system-db:
