# Generated by Django 4.2.6 on 2023-10-29 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0002_favorites_remove_applicant_grade_delete_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Самозанятость', 'Self Employment'), ('ГПХ', 'Civil Contract'), ('ТК', 'Labor Contract')])),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=800)),
                ('responsibilities', models.TextField(max_length=800)),
                ('requirements', models.TextField(max_length=800)),
                ('benefits', models.TextField(max_length=800)),
                ('status', models.CharField(choices=[('Активная', 'Active'), ('Неопубликованная', 'Unpublished'), ('Архивированная', 'Archived')], default='Активная')),
                ('employment_type', models.ManyToManyField(related_name='vacancies', to='vacancies.employment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Офис', 'Onsite'), ('Гибрид', 'Hybrid'), ('Удалённо', 'Remote')])),
            ],
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('max_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('RUB', 'Rub')])),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wage', to='vacancies.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location_type',
            field=models.ManyToManyField(related_name='vacancies', to='vacancies.worklocation'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(related_name='vacancies', to='applicants.skill'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='wage',
            constraint=models.CheckConstraint(check=models.Q(('min_amount__lt', models.F('max_amount'))), name='min_amount_lt_max_amount'),
        ),
    ]
