# Generated by Django 4.2.6 on 2023-10-30 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wage',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location_type',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_max',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_min',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='wage_currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('RUB', 'Rub')], default='USD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='wage_max',
            field=models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='wage_min',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='workplace',
            field=models.CharField(choices=[('Офис', 'Onsite'), ('Гибрид', 'Hybrid'), ('Удалённо', 'Remote')], default='Офис'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='employment_type',
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.CheckConstraint(check=models.Q(('wage_min__lt', models.F('wage_max'))), name='wage_min_lt_wage_max'),
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.CheckConstraint(check=models.Q(('experience_min__lt', models.F('experience_max'))), name='experience_min_lt_experience_max'),
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='Wage',
        ),
        migrations.DeleteModel(
            name='WorkLocation',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('Самозанятость', 'Self Employment'), ('ГПХ', 'Civil Contract'), ('ТК', 'Labor Contract')], default='ТК'),
            preserve_default=False,
        ),
    ]
